version: 0.0
os: linux
files:
- source: /	
    destination: /home/ubuntu/Debug/
    overwrite: yes
permissions:
  - object: /home/ubuntu/Debug/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
   deployment-lifecycle-event-name:
     - location: /home/ubuntu/Debug/
       timeout: timeout-in-seconds
