version: 0.0
os: linux
files:
- source: /	
    destination: /home/ubuntu/Debug/
    overwrite: yes
permissions:
  - object: /home/ubuntu/Debug/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
