name: git Action

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: my-github-action-lsm
  CODE_DEPLOY_APPLICATION_NAME: my-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-codedeploy-app-group

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout release
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: clean build -x test

    - name: Archive debug-back-deploy
      run: tar cvfz debug-back-deploy.tar.gz .

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to AWS S3
      uses: actions/aws/code-deploy@v1
      with:
        application: ${{ env.CODE_DEPLOY_APPLICATION_NAME }}
        deployment-group: ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}
        region: ${{ env.AWS_REGION }}
        wait-until-deployed: true
        codedeploy-appspec: codedeploy/appspec.yaml
